language: ruby
rvm:
 - "1.9.3"
 - "2.2"

install:
 - sudo gem install coveralls
 - sudo gem install simplecov
 - sudo gem install rtext -v 0.8.1
 - sudo gem install rgen -v 0.8.0
 - sudo gem install highline -v ">= 1.6.0"
 - sudo gem install colored
 - sudo gem install rspec

os:
 - linux
 - osx

script: rake travis
