language: ruby

matrix:
    include:
        - os: linux
          rvm: "2.0.0"
        - os: linux
          rvm: "2.1.10"
        - os: linux
          rvm: "2.2.5"
        - os: linux
          rvm: "2.3.6"
        - os: linux
          rvm: "2.4.3"
        - os: linux
          rvm: "2.5.0"
        - os: linux
          rvm: "2.6.4"
        - os: linux
          rvm: "2.7.0"
        - os: osx
          sudo: required
          rvm: "2.5.0"

install:
 - export FLAGS="--no-ri --no-rdoc"
 - echo $TRAVIS_RUBY_VERSION
 - rver=$(ruby -v | cut -c 5-10)
 - if [ $rver == 2.6.4 || $rver == 2.7.0 ]; then export FLAGS="--no-document"; fi
 - gem install coveralls $FLAGS
 - gem install simplecov -v 0.14.1 $FLAGS
 - gem install rtext -v 0.9.0 $FLAGS
 - gem install rgen -v 0.8.2 $FLAGS
 - gem install highline -v ">= 1.6.0" $FLAGS
 - gem install concurrent-ruby -v 1.0.5 $FLAGS
 - gem install thwait $FLAGS
 - gem install e2mmap $FLAGS
 - gem install colored $FLAGS
 - gem install rspec $FLAGS
 - gem install rake $FLAGS -v 12.3.3

script: rake travis
