language: ruby

matrix:
    include:
        - os: linux
          rvm: "2.0.0"
        - os: linux
          rvm: "2.1.10"
        - os: linux
          rvm: "2.2.5"
        - os: linux
          rvm: "2.3.6"
        - os: linux
          rvm: "2.4.3"
        - os: linux
          rvm: "2.5.0"
        - os: osx
          sudo: required
          rvm: "2.5.0"

install:
 - gem install coveralls --no-ri --no-rdoc
 - gem install simplecov -v 0.14.1 --no-ri --no-rdoc
 - gem install rtext -v 0.9.0 --no-ri --no-rdoc
 - gem install rgen -v 0.8.2 --no-ri --no-rdoc
 - gem install highline -v ">= 1.6.0" --no-ri --no-rdoc
 - gem install concurrent-ruby -v 1.0.5 --no-ri --no-rdoc
 - gem install colored --no-ri --no-rdoc
 - gem install rspec --no-ri --no-rdoc
 - gem install rake --no-ri --no-rdoc -v 12.3.3

script: rake travis
