language: ruby
rvm:
 - "1.9.3"
 - "2.0.0"
 - "2.1.8"
 - "2.2.4"
 - "2.3.0"
install:
 - gem install coveralls
 - gem install simplecov
 - gem install rtext -v 0.8.1
 - gem install rgen -v 0.8.0
 - gem install highline -v ">= 1.6.0"
 - gem install colored
 - gem install rspec

script: rake travis
