version: '{build}'

skip_tags: true

os: Windows Server 2012

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "22"
    - ruby_version: "25"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - gem install rtext -v 0.9.0 --no-rdoc --no-ri
  - gem install rgen -v 0.8.2 --no-rdoc --no-ri
  - gem install highline -v ">= 1.6.0" --no-rdoc --no-ri
  - gem install concurrent-ruby -v 1.0.5 --no-ri --no-rdoc
  - gem install colored --no-rdoc --no-ri
  - gem install rspec --no-rdoc --no-ri

test_script:
  - rake appveyor

build: off